### ISSUE TITLE
Iightdm fails to run with NVIDIA every boot.

### ISSUE THREAD

**Issue by h0cheung** [vetzki/nvidia-prime-switch-lightdm#1]
But after running 'sudo systenctl restart lightdm' , it runs normally.

**Comment by vetzki** [comment]
Can you copy the output of systemctl status lightdm before you restart it ?

(systemctl status lightdm > ~/lightdm_err.log in tty)

I'll switch also to lighdm and test if I encounter the issue too

best regards

**Comment by h0cheung** [comment]
> Can you copy the output of systemctl status lightdm before you restart it ?
> 
> (systemctl status lightdm > ~/lightdm_err.log in tty)
> 
> I'll switch also to lighdm and test if I encounter the issue too
> 
> best regards

● lightdm.service - Light Display Manager
   Loaded: loaded (/usr/lib/systemd/system/lightdm.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2019-01-24 10:59:06 CST; 25s ago
     Docs: man:lightdm(1)
 Main PID: 609 (lightdm)
    Tasks: 4 (limit: 4915)
   Memory: 66.6M
   CGroup: /system.slice/lightdm.service
           ├─609 /usr/bin/lightdm
           └─622 /usr/lib/Xorg -background none :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt1 -novtswitch

1月 24 10:59:06 hc-Inspiron-7472 systemd[1]: Starting Light Display Manager...
1月 24 10:59:06 hc-Inspiron-7472 systemd[1]: Started Light Display Manager.
1月 24 10:59:12 hc-Inspiron-7472 lightdm[609]: Could not find provider with name modesetting
1月 24 10:59:12 hc-Inspiron-7472 lightdm[796]: pam_unix(lightdm-greeter:session): session opened for user lightdm by (uid=0)

**Comment by vetzki** [comment]
Thats strange, as the status says loaded and active. Also last message is session opened. (no error or anything like that)

Can you show output of xrandr --listproviders after you restarted lightdm and logged in ? (can you also show output of systemctl status lightdm after restart and login?)

Least but not least if you try "intel" or "intel_modesetting" config, do you have the same issue ?

best regards,

**Comment by h0cheung** [comment]
> Thats strange, as the status says loaded and active. Also last message is session opened. (no error or anything like that)
> 
> Can you show output of xrandr --listproviders after you restarted lightdm and logged in ? (can you also show output of systemctl status lightdm after restart and login?)
> 
> Least but not least if you try "intel" or "intel_modesetting" config, do you have the same issue ?
> 
> best regards,

I changed _**modesetting**_ to _**intel**_ in **nvidia.conf** and then it runs normally without the issue.

**Comment by vetzki** [comment]
ok , but probably you're using intel driver for gpu then instead of modesetting (you can check with xrandr --listproviders). I still haven't switched to lightdm (currently I'm using no login manager) to test if I have the same issue.

Also you can test this x config and check if it solves the issue for you http://us.download.nvidia.com/XFree86/Linux-x86_64/415.18/README/randr14.html
(I'll change nvidia xorg config if it does help. Don't use nvidia-xconfig tool)

**Comment by h0cheung** [comment]
> ok , but probably you're using intel driver for gpu then instead of modesetting (you can check with xrandr --listproviders). I still haven't switched to lightdm (currently I'm using no login manager) to test if I have the same issue.
> 
> Also you can test this x config and check if it solves the issue for you http://us.download.nvidia.com/XFree86/Linux-x86_64/415.18/README/randr14.html
> (I'll change nvidia xorg config if it does help. Don't use nvidia-xconfig tool)

The same as the default nvidia.conf. Maybe there is a issue of modesetting.

**Comment by vetzki** [comment]
can you post Xorg.log?

**Comment by vetzki** [comment]
I didn't encounter any issue when using lightdm. (I also didn't get any response to the latest question)

So I'm closing the issue.

(the systemctl status output also seems like you didn't use nvidia, but either intel or modesetting)

If you still have troubles, please open a new issue (or re-open this one if possible)
